/**
 * TypeScript types for the build-time generated news index
 * This file is imported by sitemap.ts to avoid runtime filesystem reads
 */

export type BlogLang = 'en' | 'bg' | 'ru' | 'gr'

/**
 * Single news post entry in the index
 */
export interface NewsIndexEntry {
  lang: BlogLang
  slug: string
  urlPath: string
  lastmod: string // ISO date string
}

/**
 * Complete news index structure
 */
export interface NewsIndex {
  generatedAt: string // ISO date string
  totalPosts: number
  posts: NewsIndexEntry[]
}

// Static import of the build-time generated index
// This file is generated by scripts/generate-news-index.js during build
import newsIndexData from '@/content/generated/news-index.json'

/**
 * Load the news index (generated at build time)
 * This is a static import, so it will be bundled at build time
 * Includes runtime guard to handle missing/malformed JSON gracefully
 */
export function getNewsIndex(): NewsIndex {
  const data = newsIndexData as Partial<NewsIndex>
  return {
    generatedAt: data.generatedAt ?? new Date(0).toISOString(),
    totalPosts: data.totalPosts ?? (data.posts?.length ?? 0),
    posts: Array.isArray(data.posts) ? (data.posts as NewsIndexEntry[]) : [],
  }
}

/**
 * Get all news posts for a specific language
 */
export function getNewsPostsForLang(lang: BlogLang): NewsIndexEntry[] {
  const index = getNewsIndex()
  return index.posts.filter((post) => post.lang === lang)
}
